ALTER TABLE "Supplier"
ADD COLUMN "profileScore" INTEGER NOT NULL DEFAULT 70,
ADD COLUMN "complianceScore" INTEGER NOT NULL DEFAULT 70,
ADD COLUMN "deliveryScore" INTEGER NOT NULL DEFAULT 70,
ADD COLUMN "qualityScore" INTEGER NOT NULL DEFAULT 70,
ADD COLUMN "riskScore" INTEGER NOT NULL DEFAULT 70;
